version: '3'
services:
  translator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - translator:/app
    env_file:
      - stack.env

  # ngrok:
  #   image: ngrok/ngrok
  #   depends_on:
  #     - translator
  #   env_file:
  #     - stack.env
  #   command: http 127.0.0.1:3000
  #   stdin_open: true
  #   tty: true

volumes:
  translator: