version: '3'
services:
  translator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./translator:/app
    env_file:
      - stack.env

  ngrok:
    image: ngrok/ngrok
    depends_on:
      - translator
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http 127.0.0.1:3000
